### ISSUE TITLE
Reactive line clamps

### ISSUE THREAD

**Issue by akbarkz** [Frondor/vue-line-clamp#1]
Hey man!
You have created an awesome tool, that's exactly what I was looking for, since none of other solutions worked nicely with Vue.js.
But is value of v-line-clamp reactive? If I change the value of variable, that I assign to v-line-clamp, would number of lines in p change accordingly?

**Comment by Frondor** [comment]
Thank you!
No, it isn't reactive and the only way you can get such behavior at the moment is by implementing something with `$forceUpdate` just like in the [demo](https://codepen.io/Frondor/pen/ypvPEQ?editors=1010) (which is not working atm, I'll fix it later).

I want to keep it as simple and lightweight as possible but might be a good idea to implement something like that, for cases such a readmore or kind of.
Need to change lot of things actually so I'll work on that, on a upcoming version, probably this weekend.

**Comment by akbarkz** [comment]
Awesome! Thank you!

**Comment by Frondor** [comment]
This is now implemented in **v1.2** :wink:
