### ISSUE TITLE
Problem with custom font Inter UI

### ISSUE THREAD

**Issue by tmvst** [Frondor/vue-line-clamp#15]
Hello, I'm using a custom font called [Inter UI](https://rsms.me/inter/) and line clamping doesn't work properly.

[Screenshot](http://files.tmv.st/sCdf)

- I'm running Vue via webpacker gem with Ruby on Rails
- I'm loading the font via `@import url("https://rsms.me/inter/inter-ui.css");` in my SCSS in Rails asset pipeline
- I'm using line clamp like this: `<p class="post__data__content" v-line-clamp="{ 
          lines: 1,
          text: post.content
        }"></p>`

Am I doing something wrong, or is there any fix for this behaviour? Thanks

**Comment by Frondor** [comment]
Hello @tmvst

It's hard for me to tell what's going on in your layout. But I'm pretty sure some style is getting overriden, not a font-related problem.
It would be cool if you provide a live example of that, so I can try to address the issue and fix it if needed.

Also, you're passing an object as the directive. That's not how it works.
See the live demo here: https://codepen.io/Frondor/pen/ypvPEQ

It should be
```html
<!-- lines is a number in your instance -->
<p class="post__data__content" v-line-clamp="lines">{{  post.content }}</p>
```

**Comment by tmvst** [comment]
Hello @Frondor 

Thanks for the response.
I'll try to set up a live demo of the problem in a moment.

Regarding my implementation, passing that object is the only way this works for me. If I do it as you suggested, no text renders in the `<p>` tag. 🤷‍♂️

**Comment by tmvst** [comment]
Okay, I found out that this problem only occurs when I have the devtools open. So I guess it's linked to a disabled cache or something?

**Comment by Frondor** [comment]
> Regarding my implementation, passing that object is the only way this works for me

How is that even possible? The API doesn't accepts nor read any object, it just expects an integer.
You must be getting the following exception
https://github.com/Frondor/vue-line-clamp/blob/78271d39215be15233640a58e19a5773159a791f/src/main.js#L25

> If I do it as you suggested, no text renders in the <p> tag

Isn't that what you wanted in your example? Why would you set a line-clamp on that `p` tag, if you're not placing the text inside it?

Looks like this is not an actual issue. Are you sure you've installed this package?

**Comment by Frondor** [comment]
The API you're using looks pretty much like vue-line-clamp-extended package. This is the original `vue-line-clamp` for cross-browser handling of the line-clamp technique.

**Comment by tmvst** [comment]
Oh my god I'm so sorry. Yes I'm using the extended version, I didn't notice 🙊.
I'm very sorry to waste your time. Thank you for your patience!

**Comment by Frondor** [comment]
It's not an "extended" version though. It's totally different from this package. Main difference is browser support.
Closing this.
