### ISSUE TITLE
IE11 - Object does not support property or method 'assign'

### ISSUE THREAD

**Issue by srogalsky8** [Frondor/vue-line-clamp#16]
![image](https://user-images.githubusercontent.com/4275725/42860362-e591f96a-8a0a-11e8-96ac-5082db9e8c4a.png)

Setup a vue project initially using vue-cli

Screen is blank in IE11 and the above error is seen.  This happens when importing vue-line-clamp into a component (.vue file) and calling `Vue.use(lineClamp, {})` there.  However, when importing it into my main.js file (and I'm guess any .js file), there is no issue.  For some reason it seems that the polyfill for Object.assign does not get used unless importing into a js file.  Could this be an issue with vue-loader or babel-loader?

**Comment by Frondor** [comment]
Hello!

Babel is not aware of the polyfill it has to load for your project dependencies unless you do some "trickery". This is a known issue and happens on most projects.

> Our babel preset uses babel-preset-env, and by default, we set that preset's useBuiltIns option to usage, which means it will only include polyfills for stuff that it actually comes "across" while compiling.
> 
> However, since we don't transpile node_modules, any lib that uses ES6 features won't automatically have that feature polyfilled until we ourselves use that feature in our own, transpiling code.
> 
> The solution is to set useBuiltIns: entry as an option to our preset and import the polyfill in main.js:
> 
> ```
> {
>   "presets": [
>     [
>       "@vue/app", 
>       {
>         "useBuiltIns": "entry"
>       }
>     ]
>   ]
> }
> ```
> ```
> // main.js
> import '@babel/polyfill'
> import Vue from 'vue'
> // ..
> ```

Anyway, you're not supposed to call `Vue.use()` inside components.
Even if you want to call `Vue.use` inside a SFC, the plugin is not aware of that, and all the components / directives / services it is installing, those are going to be globally registered anyway.

I might need to add a new section in the README talking about this. But for now, you may want to pay a look to these issues. 
https://github.com/vuetifyjs/vue-cli-plugin-vuetify/issues/3#issuecomment-385357316
https://github.com/vuejs/vue-cli/issues/1248#issue-321470161

**Comment by srogalsky8** [comment]
Thanks for the quick response!

Yes, it does look to be babel's issue with the polyfill only being detected when modules are imported into the entry point. 

We actually happen to be using some imports in components which are included in multiple vue apps (we have multiple entry points and index.html outputs for these) and that's why I was looking to include the dependency in the shared component.  We can get the plugin working by doing the import and install in each of the main.js files (or importing babel-polyfill if we really wanted to).

Anyway, I also come across the new vue-cli docs which mentioned the issue with polyfills and useBuiltIns:

https://cli.vuejs.org/guide/browser-compatibility.html#polyfills

I wasn't exactly sure how babel was resolving which polyfills to include, so thanks for the knowledge.

**Comment by Frondor** [comment]
Me neither! So thank you for making me aware of that :smile: 
Glad you've solved this.
