### ISSUE TITLE
Not working for firefox 64 

### ISSUE THREAD

**Issue by azayati** [Frondor/vue-line-clamp#23]
Hello,
It is not working with FF 64.0.2 (64 bits), any workaround for that issue ?

Thanks,

**Comment by Frondor** [comment]
Hey,
What's the problem? Got any screenshot? error log?

**Comment by azayati** [comment]
hello,
No error but the ellipsis is not shown

**Comment by Frondor** [comment]
Alright, then it's not an issue actually, please see #17 
It's a known limitation I'm afraid.

**Comment by azayati** [comment]
I guess that in order to get a complete solution. We should find a way to make this module working for all browsers

**Comment by Frondor** [comment]
It does work in all browsers as per the description states, but the scope is different. I guess I should include that in the readme 🤔 
You can read the argument in my last comment of that issue: https://github.com/Frondor/vue-line-clamp/issues/17#issuecomment-435506685
